### PR TITLE
Shell Evaluate

### PR DESCRIPTION
**Pull request by weichuliu**
This implements #6.

The code is tested on Sublime3/macOS, and works.

If I have time, I will try to do more test but I'm not sure if I have time.

- [ ] Test on Windows (ST2/3)
- [ ] Test on Linux (ST2/3)
- [ ] Test on macOS (ST2)

### CODE REVIEW

**Comment by weichuliu** [comment]
Hi @jbrooksuk any comments on the codes?
Please tell me if you want me to change/fix somewhere.

**Comment by jbrooksuk** [comment]
Sorry! Currently in NYC at a conference. I'll review properly once I'm back :)

**Comment by weichuliu** [comment]
Hi @jbrooksuk any update for this PR?

I've been using this on my mac for three months, it works perfectly and is pretty convenience 😸 
Let me know if you would like to accept this PR.

**Comment by jbrooksuk** [comment]
LGTM!

**Pull request merged**
